"""The Hit Character pool draw (block schema 2): shared vectors and guarantees.

`fixtures/ctr_hit_roster_vectors.json` is a byte-identical copy of native
`tools/fixtures/ctr_hit_roster_vectors.json` (generated by native
`tools/gen-hit-roster-vectors.py`). Native replays it through its production
draw; this file replays it through the apworld's independent
`reference_draw`, so the two implementations are cross-checked.

The guarantee tests are the logic proof the Hit rules rely on
(`hit_character` module comment, G1 to G5): with a fixed player racer and
repeated fresh draws at one destination, every eligible target other than the
player is seated within a bound, and under the strategy "hit every seated
target whose Hit is unchecked" every one of them is hit within a bound.
"""
import hashlib
import itertools
import json
import os
import random
import unittest

from ..hit_character import (
    CURSOR_INIT,
    MAX_GUESTS,
    reference_draw,
    reference_opportunity,
    stock,
)

FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures",
                       "ctr_hit_roster_vectors.json")
#: SHA-256 of the native fixture this copy must equal byte for byte.
FIXTURE_SHA256 = "d33c173eda0edda73a2248350b10a7725ee0b53b4738d7d2df80b46d7130f662"

ORDINARY = 7
PURPLE = 4


def _flags(ids):
    out = [0] * 16
    for cid in ids:
        out[cid] = 1
    return out


def _eligible(guests):
    return [1] * 8 + [1 if cid in set(guests) else 0 for cid in range(8, 16)]


def _load():
    with open(FIXTURE, "rb") as handle:
        raw = handle.read()
    return raw, json.loads(raw)


class TestSharedVectors(unittest.TestCase):
    def test_fixture_is_the_native_copy(self):
        raw, data = _load()
        self.assertEqual(hashlib.sha256(raw).hexdigest(), FIXTURE_SHA256)
        self.assertEqual(data["schema"], 2)
        self.assertEqual(data["algorithm"], "unhit_first_rotation")
        self.assertEqual(data["max_guests"], MAX_GUESTS)
        self.assertEqual(data["cursor_init"], CURSOR_INIT)

    def test_draw_cases(self):
        _raw, data = _load()
        self.assertGreater(len(data["draw_cases"]), 50)
        for case in data["draw_cases"]:
            with self.subTest(case=case["name"]):
                field, cursors = reference_draw(
                    case["order"], case["player"],
                    _eligible(case["eligible_guests"]),
                    _flags(case["unchecked"]), case["ai_seats"],
                    list(case["cursors_in"]))
                self.assertEqual(field, case["field"])
                self.assertEqual(cursors, case["cursors_out"])
                st = set(stock(case["player"]))
                self.assertEqual([c for c in field if c not in st],
                                 case["extras"])

    def test_sequence_cases(self):
        _raw, data = _load()
        self.assertGreater(len(data["sequence_cases"]), 5)
        for case in data["sequence_cases"]:
            cursors = [CURSOR_INIT] * 3
            for index, step in enumerate(case["steps"]):
                with self.subTest(case=case["name"], step=index):
                    field, cursors = reference_draw(
                        case["order"], case["player"],
                        _eligible(step["eligible_guests"]),
                        _flags(step["unchecked"]), case["ai_seats"], cursors)
                    self.assertEqual(field, step["field"])
                    self.assertEqual(cursors, step["cursors_out"])

    def test_opportunity_cases(self):
        _raw, data = _load()
        for case in data["opportunity_cases"]:
            with self.subTest(case=case["name"]):
                self.assertEqual(
                    reference_opportunity(case["player"],
                                          _eligible(case["eligible_guests"]),
                                          _flags(case["unchecked"])),
                    case["target"])


def _orders():
    """Identity, reversed and a few seeded shuffles."""
    orders = [list(range(16)), list(range(15, -1, -1))]
    for seed in (1, 2, 3):
        order = list(range(16))
        random.Random(seed).shuffle(order)
        orders.append(order)
    return orders


def _states():
    """(player, unlocked guests, unchecked set) covering every player and
    every unlocked-guest subset, with all-unchecked plus sampled unchecked."""
    rng = random.Random(20260914)
    for player in range(16):
        for mask in range(256):
            guests = [8 + bit for bit in range(8) if mask >> bit & 1]
            yield player, guests, list(range(16))
            yield player, guests, [c for c in range(16)
                                   if rng.random() < 0.6]


class TestInvariants(unittest.TestCase):
    """Every draw: full field, no duplicate, never the player, extras <= 3."""

    def test_every_single_draw(self):
        for order in _orders()[:2]:
            for player, guests, unchecked in _states():
                elig, unc = _eligible(guests), _flags(unchecked)
                for seats in (ORDINARY, PURPLE):
                    for start in range(16):
                        field, cur = reference_draw(order, player, elig, unc,
                                                    seats, [start] * 3)
                        self.assertEqual(len(field), seats)
                        self.assertEqual(len(set(field)), seats)
                        self.assertNotIn(player, field)
                        st = set(stock(player))
                        self.assertLessEqual(
                            len([c for c in field if c not in st]), MAX_GUESTS)
                        self.assertTrue(all(elig[c] for c in field))
                        self.assertTrue(all(0 <= c <= 15 for c in cur))

    def test_stock_matches_the_engine_robot_set(self):
        self.assertEqual(stock(0), [1, 2, 3, 4, 5, 6, 7])
        self.assertEqual(stock(3), [0, 1, 2, 4, 5, 6, 7])
        self.assertEqual(stock(7), [0, 1, 2, 3, 4, 5, 6])
        for player in range(8, 16):
            self.assertEqual(stock(player), [0, 1, 2, 3, 4, 5, 6])


class TestGuarantees(unittest.TestCase):
    """G1 to G4 with the pools held fixed, over every start cursor."""

    def test_g1_to_g4(self):
        for order in _orders()[1:3]:
            for player, guests, unchecked in _states():
                elig, unc = _eligible(guests), _flags(unchecked)
                unhit = [c for c in guests if c != player and unc[c]]
                st = set(stock(player))
                for start in range(16):
                    cursors = [start] * 3
                    seen = []
                    for _ in range(6):
                        field, cursors = reference_draw(
                            order, player, elig, unc, ORDINARY, cursors)
                        seen.append(set(field))
                        if len(unhit) <= 3:  # G1: every race
                            self.assertTrue(set(unhit) <= set(field))
                    # G2: any ceil(n/3) consecutive draws cover the unhit set.
                    window = max(1, -(-len(unhit) // 3))
                    for i in range(len(seen) - window + 1):
                        covered = set().union(*seen[i:i + window])
                        self.assertTrue(set(unhit) <= covered,
                                        (order, player, guests, unchecked))
                    # G3: any 2 consecutive draws cover the stock set.
                    for i in range(len(seen) - 1):
                        self.assertTrue(st <= seen[i] | seen[i + 1])
                    # G4: with a free extra slot the other non-stock ids
                    # rotate: all seen within ceil(|X| / free) draws.
                    free = MAX_GUESTS - min(len(unhit), MAX_GUESTS)
                    other = [c for c in range(16) if c != player
                             and c not in st and elig[c] and c not in unhit]
                    if free and other:
                        span = -(-len(other) // free)
                        if span <= len(seen):
                            for i in range(len(seen) - span + 1):
                                covered = set().union(*seen[i:i + span])
                                self.assertTrue(set(other) <= covered)


class TestLogicStrategy(unittest.TestCase):
    """G5: re-race one destination, hit every seated unchecked target.

    Starting from every player, every unlocked-guest set and all Hits
    unchecked, every eligible target other than the player is hit within
    `BOUND` races. Unlocks may also arrive mid-way (monotone growth), which
    only adds targets; the bound is asserted from the last unlock.
    """

    BOUND = 6

    def _run(self, order, player, unlock_schedule):
        unchecked = _flags(range(16))
        cursors = [CURSOR_INIT] * 3
        guests = []
        races_since_change = 0
        for race in range(40):
            if race in unlock_schedule:
                guests = sorted(set(guests) | set(unlock_schedule[race]))
                races_since_change = 0
            elig = _eligible(guests)
            targets = {c for c in range(16)
                       if c != player and elig[c] and unchecked[c]}
            if not targets and race > max(unlock_schedule, default=0):
                return races_since_change
            field, cursors = reference_draw(order, player, elig, unchecked,
                                            ORDINARY, cursors)
            for cid in field:
                unchecked[cid] = 0
            races_since_change += 1
        self.fail(f"targets left after 40 races: order={order} "
                  f"player={player} schedule={unlock_schedule}")

    def test_every_target_is_hit_within_the_bound(self):
        worst = 0
        for order in _orders():
            for player in range(16):
                for mask in range(256):
                    guests = [8 + b for b in range(8) if mask >> b & 1]
                    worst = max(worst, self._run(order, player, {0: guests}))
        self.assertLessEqual(worst, self.BOUND)

    def test_unlocks_arriving_between_races(self):
        rng = random.Random(7)
        for order in _orders():
            for player in range(16):
                for _ in range(20):
                    guests = list(range(8, 16))
                    rng.shuffle(guests)
                    schedule = {}
                    race = 0
                    for guest in guests:
                        race += rng.randint(0, 2)
                        schedule.setdefault(race, []).append(guest)
                    self.assertLessEqual(self._run(order, player, schedule),
                                         self.BOUND)

    def test_hit_nothing_still_seats_every_unhit_guest(self):
        """Even a player who hits nobody meets every unhit unlocked guest
        within ceil(n/3) races (only Pura for a non-default player can wait
        for guest hits, which the strategy above covers)."""
        for order in _orders():
            for player, guests in itertools.product(range(16), [list(range(8, 16))]):
                unc = _flags(range(16))
                elig = _eligible(guests)
                cursors = [CURSOR_INIT] * 3
                seen = set()
                for _ in range(3):
                    field, cursors = reference_draw(order, player, elig, unc,
                                                    ORDINARY, cursors)
                    seen |= set(field)
                self.assertTrue({g for g in guests if g != player} <= seen)


if __name__ == "__main__":
    unittest.main()
